add error checking

diff --git a/umberella b/umberella
--- a/umberella
+++ b/umberella
@@ -1,10 +1,25 @@
 #!/usr/bin/env bash
 
 CACHE_DIR="$HOME/.cache"
+REPORT_FILE="$CACHE_DIR/umberella"
 
+# If .cache is not directory
 if ! [[ -d $CACHE_DIR ]]; then
 	mkdir "$CACHE_DIR"
 fi
 
-REPORT=$(curl -s wttr.in | head -n 7)
-echo "$REPORT"
+# If failed, check for non-cached data. 
+if [[ $? && -s $REPORT_FILE ]]; then
+	echo "Unable to contact to source."
+	echo "Loading from cache..."
+  
+	# Even single charecter means empty. 
+	chars=$(wc -m "$REPORT_FILE" | cut -d ' ' -f1)
+
+	if (( chars <= 1)) ; then
+		echo "Cannot load the cached data. Exiting...."
+		exit 1
+	fi
+fi
+
+cat "$REPORT_FILE"
